version: "3"

services:
    spark:
        image: gudev/spark-jupyterlab:2.3.2
        container_name: spark-jupyterlab
        ports:
            - "8888:8888" # Jupyterlab
            - "4040:4040" # Spark 웹 UI
        volumes:
            - "./data:/data"
            - "./book-code:/code"
            - "./jupyterlab-notebooks:/jupyter"
            - "./spark-warehouse:/spark/spark-warehouse"

        restart: unless-stopped
