version: "3"

services:
    spark-practice:
        image: gudev/spark_zeppelin_arm64:1.0.0
        container_name: spark_zeppelin_arm64
        ports:
            - "8080:8080" # Zeppelin 포트를 호스트와 매핑
            - "4040:4040" # Spark 웹 UI 포트를 호스트와 매핑
        volumes:
            - "./data:/data" # 필요한 경우 호스트의 데이터 디렉토리를 컨테이너의 데이터 디렉토리에 마운트
            - "./notebooks:/zeppelin/notebook" # Zeppelin 노트북을 호스트와 동기화
        environment:
            - ZEPPELIN_ADDR=0.0.0.0
        restart: unless-stopped
